[package]
name = "grim-doc"
version = "0.0.1"
edition.workspace = true 
description = "Documentation for the Grim programing language."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
